name: Build CentiloidCalculator

on: [push, pull_request]

env:
  ONNXRUNTIM_VERSION: 1.20.1  # 可根据需要更新为最新版本

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}-2025-03-09
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Install vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0'  # 替换为实际最新 SHA1
          vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'

      - name: Install dependencies via vcpkg
        run: |
          .\vcpkg\vcpkg install itk simpleitk onnxruntime --recurse

      - name: Build with CMake
        run: |
          cmake -S cpp -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CentiloidCalculator-windows
          path: build/Release/CentiloidCalculator.exe

  build-macos:
    name: Build on macOS
    runs-on: macOS-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ITK and SimpleITK via Homebrew
        run: |
          brew install itk simpleitk

      - name: Download ONNX Runtime binary
        run: |
          curl -L -o onnxruntime.tar.gz "https://github.com/microsoft/onnxruntime/releases/download/v${{ env.ONNXRUNTIM_VERSION }}/onnxruntime-osx-x64-${{ env.ONNXRUNTIM_VERSION }}.tgz"
          tar -xzf onnxruntime.tar.gz

      - name: Set extracted directory name
        run: |
          EXTRACTED_DIR=onnxruntime-osx-x64-${{ env.ONNXRUNTIM_VERSION }}
          echo "EXTRACTED_DIR=$EXTRACTED_DIR" >> $GITHUB_ENV

      - name: Build with CMake
        run: |
          cmake -S cpp -B build -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/${{ env.EXTRACTED_DIR }}
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CentiloidCalculator-macos
          path: build/CentiloidCalculator

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ITK and SimpleITK
        run: |
          sudo apt-get update
          sudo apt-get install -y libinsighttoolkit5-dev libsimpleitk1-dev

      - name: Download ONNX Runtime binary
        run: |
          curl -L -o onnxruntime.tar.gz "https://github.com/microsoft/onnxruntime/releases/download/v${{ env.ONNXRUNTIM_VERSION }}/onnxruntime-linux-x64-${{ env.ONNXRUNTIM_VERSION }}.tgz"
          tar -xzf onnxruntime.tar.gz

      - name: Set extracted directory name
        run: |
          EXTRACTED_DIR=onnxruntime-linux-x64-${{ env.ONNXRUNTIM_VERSION }}
          echo "EXTRACTED_DIR=$EXTRACTED_DIR" >> $GITHUB_ENV

      - name: Build with CMake
        run: |
          cmake -S cpp -B build -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/${{ env.EXTRACTED_DIR }}
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CentiloidCalculator-linux
          path: build/CentiloidCalculator